=== IMGSaibh/motion_viz/src/backend/data_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "format": {
            "type": "string",
            "enum": [
                "pkl",
                "npz",
                "npy",
                "bvh",
                "csv",
                "cdf",
                "mmm",
                "matlab",
                "mvnx",
                "converter",
                "c3d"
            ],
            "default": "csv"
        },
        "abbrev": {
            "type": "string",
            "default": ""
        },
        "scale": {
            "type": "integer",
            "default": 1
        },
        "positions": {
            "type": "string",
            "enum": [
                "relative",
                "absolute",
                "none"
            ],
            "default": "absolute"
        },
        "data-order": {
            "type": "array",
            "items": {
                "type": "number",
                "minItems": 3,
                "maxItems": 3,
                "uniqueItems": true
            }
        },
        "dim-order": {
            "type": "array",
            "items": {
                "type": "number",
                "minItems": 3,
                "maxItems": 3,
                "uniqueItems": true
            }
        },
        "rotations": {
            "type": "string",
            "enum": [
                "relative",
                "absolute",
                "none"
            ],
            "default": "none"
        },
        "rotation-representation": {
            "type": "string",
            "enum": [
                "euler_xyz",
                "euler_xzy",
                "euler_yxz",
                "euler_yzx",
                "euler_zxy",
                "euler_zyx",
                "quaternion_xyzw",
                "quaternion_wxyz",
                "axis-angle"
            ],
            "default": "quaternion_wxyz"
        },
        "systemname": {
            "type": "string",
            "default": ""
        },
        "npz-array-name": {
            "type": "string",
            "default": ""
        },
        "pickle-array-name": {
            "type": "string",
            "default": ""
        },
        "header-size": {
            "type": "integer",
            "minimum": 0,
            "default": 0
        },
        "separator": {
            "type": "string"
        },
        "joint-graph": {
            "type": "array"
        },
        "joint-pos-cols": {
            "type": "array"
        },
        "joint-rot-cols": {
            "type": "array"
        },
        "fps": {
            "type": "number",
            "default": 30
        }
    },
    "required": [
        "format",
        "systemname",
        "fps",
        "dim-order",
        "scale",
        "abbrev",
        "positions",
        "rotations"
    ],
    "if": {
        "properties": {
            "format": {
                "const": "matlab"
            }
        }
    },
    "then": {
        "required": [
            "matlab-array-name"
        ]
    },
    "anyOf": [
        {
            "properties": {
                "format": {
                    "enum": [
                        "bvh",
                        "mvnx"
                    ]
                }
            }
        },
        {
            "required": [
                "joint-graph"
            ]
        }
    ],
    "allOf": [
        {
            "if": {
                "properties": {
                    "format": {
                        "const": "csv"
                    }
                }
            },
            "then": {
                "required": [
                    "header-size"
                ]
            }
        },
        {
            "if": {
                "properties": {
                    "format": {
                        "const": "csv"
                    }
                }
            },
            "then": {
                "required": [
                    "separator"
                ]
            }
        },
        {
            "if": {
              "allOf": [
                {
                  "properties": {
                    "positions": {
                      "const": "none"
                    }
                  }
                },
                {
                  "not": {
                    "properties": {
                      "format": {
                        "const": "bvh"
                      }
                    }
                  }
                }
              ]
            },
            "then": {
              "required": ["joint-offsets"]
            }
          },
        {
            "if": {
                "required": [
                    "joint-offsets"
                ]
            },
            "then": {
                "required": [
                    "offset-type"
                ]
            }
        },
        {
            "if": {
                "properties": {
                    "format": {
                        "const": "pkl"
                    }
                }
            },
            "then": {
                "required": [
                    "pickle-array-name"
                ]
            }
        },
        {
            "if": {
                "properties": {
                    "format": {
                        "const": "cdf"
                    }
                }
            },
            "then": {
                "required": [
                    "data-array-name"
                ]
            }
        },
        {
            "if": {
                "properties": {
                    "format": {
                        "const": "npz"
                    }
                }
            },
            "then": {
                "required": [
                    "npz-array-name"
                ]
            }
        },
        {
            "if": {
                "properties": {
                    "format": {
                        "const": "converter"
                    }
                }
            },
            "then": {
                "required": [
                    "converter"
                ]
            }
        }
    ],
    "additionalProperties": true
}

=== IMGSaibh/motion_viz/data/descriptor_files/mvnx.json
{
  "systemname": "Movella XSens",
  "format": "mvnx",
  "abbrev":"XSens",
  "positions": "absolute",
  "rotations": "relative",
  "rotation-representation": "quaternion_xyzw",
  "fps": 60,
  "dim-order": [0,2,1],
  "scale":1,
  "joint-graph": [
    {
      "id": 0,
      "pid": -1,
      "name": "Pelvis"
    },
    {
      "id": 1,
      "pid": 0,
      "name": "jL5S1"
    },
    {
      "id": 2,
      "pid": 1,
      "name": "jL4L3"
    },
    {
      "id": 3,
      "pid": 2,
      "name": "jL1T12"
    },
    {
      "id": 4,
      "pid": 3,
      "name": "jT9T8"
    },
    {
      "id": 5,
      "pid": 4,
      "name": "jT1C7"
    },
    {
      "id": 6,
      "pid": 5,
      "name": "jC1Head"
    },
    {
      "id": 7,
      "pid": 4,
      "name": "jRightT4Shoulder"
    },
    {
      "id": 8,
      "pid": 7,
      "name": "jRightShoulder"
    },
    {
      "id": 9,
      "pid": 8,
      "name": "jRightElbow"
    },
    {
      "id": 10,
      "pid": 9,
      "name": "jRightWrist"
    },
    {
      "id": 11,
      "pid": 4,
      "name": "jLeftT4Shoulder"
    },
    {
      "id": 12,
      "pid": 11,
      "name": "jLeftShoulder"
    },
    {
      "id": 13,
      "pid": 12,
      "name": "jLeftElbow"
    },
    {
      "id": 14,
      "pid": 13,
      "name": "jLeftWrist"
    },
    {
      "id": 15,
      "pid": 0,
      "name": "jRightHip"
    },
    {
      "id": 16,
      "pid": 15,
      "name": "jRightKnee"
    },
    {
      "id": 17,
      "pid": 16,
      "name": "jRightAnkle"
    },
    {
      "id": 18,
      "pid": 17,
      "name": "jRightBallFoot"
    },
    {
      "id": 19,
      "pid": 0,
      "name": "jLeftHip"
    },
    {
      "id": 20,
      "pid": 19,
      "name": "jLeftKnee"
    },
    {
      "id": 21,
      "pid": 20,
      "name": "jLeftAnkle"
    },
    {
      "id": 22,
      "pid": 21,
      "name": "jLeftBallFoot"
    }
  ]
}
